version: "3.6"

services:

  pinot-controller:
    image: apachepinot/pinot:latest-arm64
    restart: unless-stopped
    command: StartController -zkAddress pinot-zoo
    depends_on:
      - pinot-zoo
    expose:
      - "9000"
    ports:
      - "9000:9000"
    networks:
      - pinpoint

  pinot-broker-0:
    image: apachepinot/pinot:latest-arm64
    restart: unless-stopped
    command: StartBroker -zkAddress pinot-zoo
    depends_on:
      - pinot-controller
    expose:
      - "8099"
    networks:
      - pinpoint

  pinot-server-0:
    image: apachepinot/pinot:latest-arm64
    restart: unless-stopped
    command: StartServer -zkAddress pinot-zoo
    depends_on:
      - pinot-broker-0
    expose:
      - "8098"
    networks:
      - pinpoint

  pinot-init:
    image: apachepinot/pinot:latest-arm64
    restart: "no"
    entrypoint: >
      sh -c "
      curl https://raw.githubusercontent.com/pinpoint-apm/pinpoint/v${PINPOINT_VERSION}/metric-module/metric/src/main/pinot/pinot-uriStat-table.json > uriStatTable.json &&
      curl https://raw.githubusercontent.com/pinpoint-apm/pinpoint/v${PINPOINT_VERSION}/metric-module/metric/src/main/pinot/pinot-uriStat-schema.json > uriStatSchema.json &&
      curl https://raw.githubusercontent.com/pinpoint-apm/pinpoint/v${PINPOINT_VERSION}/metric-module/metric/src/main/pinot/pinot-tag-table.json > tagTable.json &&
      curl https://raw.githubusercontent.com/pinpoint-apm/pinpoint/v${PINPOINT_VERSION}/metric-module/metric/src/main/pinot/pinot-tag-schema.json > tagSchema.json &&
      curl https://raw.githubusercontent.com/pinpoint-apm/pinpoint/v${PINPOINT_VERSION}/metric-module/metric/src/main/pinot/pinot-double-table.json > doubleTable.json &&
      curl https://raw.githubusercontent.com/pinpoint-apm/pinpoint/v${PINPOINT_VERSION}/metric-module/metric/src/main/pinot/pinot-double-schema.json > doubleSchema.json &&
      curl https://raw.githubusercontent.com/pinpoint-apm/pinpoint/v${PINPOINT_VERSION}/metric-module/metric/src/main/pinot/pinot-dataType-table.json > dataTypeTable.json &&
      curl https://raw.githubusercontent.com/pinpoint-apm/pinpoint/v${PINPOINT_VERSION}/metric-module/metric/src/main/pinot/pinot-dataType-schema.json > dataTypeSchema.json &&

      sed -i 's/localhost:19092/pinpoint-kafka:9092/g' uriStatTable.json tagTable.json doubleTable.json dataTypeTable.json &&

      sleep 30 &&
      /opt/pinot/bin/pinot-admin.sh AddTable -schemaFile uriStatSchema.json -realtimeTableConfigFile uriStatTable.json -controllerHost pinot-controller -controllerPort 9000 -exec &&
      /opt/pinot/bin/pinot-admin.sh AddTable -schemaFile tagSchema.json -realtimeTableConfigFile tagTable.json -controllerHost pinot-controller -controllerPort 9000 -exec &&
      /opt/pinot/bin/pinot-admin.sh AddTable -schemaFile doubleSchema.json -realtimeTableConfigFile doubleTable.json -controllerHost pinot-controller -controllerPort 9000 -exec &&
      /opt/pinot/bin/pinot-admin.sh AddTable -schemaFile dataTypeSchema.json -realtimeTableConfigFile dataTypeTable.json -controllerHost pinot-controller -controllerPort 9000 -exec"
    depends_on:
      - pinot-server-0
      - pinpoint-kafka-init
    networks:
      - pinpoint